set(SETUP_SCRIPT_FILENAME "${CMAKE_BINARY_DIR}/setup")
message(STATUS "Writing environment setup to ${SETUP_SCRIPT_FILENAME}")

file(WRITE ${SETUP_SCRIPT_FILENAME}
  "export GPGPUSIM_SETUP_ENVIRONMENT_WAS_RUN=1\n")
file(APPEND ${SETUP_SCRIPT_FILENAME}
  "export GPGPUSIM_ROOT=${PROJECT_SOURCE_DIR}\n")
file(APPEND ${SETUP_SCRIPT_FILENAME}
  "export GPGPUSIM_CONFIG=${GPGPUSIM_CONFIG}\n")
file(APPEND ${SETUP_SCRIPT_FILENAME}
  "export CUDA_INSTALL_PATH=${CUDAToolkit_TARGET_DIR}\n")
file(APPEND ${SETUP_SCRIPT_FILENAME}
  "export CUDA_VERSION_NUMBER=11080\n")
file(APPEND ${SETUP_SCRIPT_FILENAME}
  "export PATH=${PROJECT_SOURCE_DIR}/bin:${CUDAToolkit_BIN_DIR}:\$PATH\n")
file(APPEND ${SETUP_SCRIPT_FILENAME}
  "export LD_LIBRARY_PATH=${GPGPUSIM_INSTALL_PATH}:\${LD_LIBRARY_PATH:-}\n")
